/*
 * 
 *TODO:
  +Adding Airports
  +Edit Flights
  +Delete Flights
 */
package airportx;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Objects;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author AVA
 */
public class AirportXUI extends javax.swing.JFrame {

    /**
     * Creates new form AirportXUI
     */
    ArrayList<Flight> allFlights = new ArrayList<Flight>();
    ArrayList<Airport> allAirports = new ArrayList<Airport>();

    String currentAirport = "";

    public AirportXUI() {

        allAirports.add(new Airport("IST"));
        allAirports.add(new Airport("DUB"));
        allAirports.add(new Airport("CDG"));
        allAirports.add(new Airport("DXB"));
        allAirports.add(new Airport("JFK"));
        allAirports.add(new Airport("YUL"));
        for (int i = 0; i < 300; i++) {
            System.out.println(i);
            allFlights.add(DataGen.randomFlight(allAirports, allFlights));
        }
        initComponents();
        //Collections.sort(allFlights);
        for (int i = 0; i < allAirports.size(); i++) {
            jComboBox1.addItem(allAirports.get(i).getCode());
        }

        System.out.println(DataGen.randomBday());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIn = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableOut = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextA1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextA3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextA5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextA4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextA7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextA6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextA9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextA2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextA8 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        jTableIn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Plane ID", "Carrier", "Source", "Destination", "Departure ", "Arrival", "Crew", "Gate ", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableIn.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableIn);
        if (jTableIn.getColumnModel().getColumnCount() > 0) {
            jTableIn.getColumnModel().getColumn(0).setResizable(false);
            jTableIn.getColumnModel().getColumn(1).setResizable(false);
            jTableIn.getColumnModel().getColumn(2).setResizable(false);
            jTableIn.getColumnModel().getColumn(3).setResizable(false);
            jTableIn.getColumnModel().getColumn(4).setResizable(false);
            jTableIn.getColumnModel().getColumn(5).setResizable(false);
            jTableIn.getColumnModel().getColumn(6).setResizable(false);
            jTableIn.getColumnModel().getColumn(7).setResizable(false);
            jTableIn.getColumnModel().getColumn(8).setResizable(false);
            jTableIn.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Incoming ", jPanel1);

        jTableOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Plane ID", "Carrier", "Source", "Destination", "Departure ", "Arrival", "Crew", "Gate ", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOut.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTableOut);
        if (jTableOut.getColumnModel().getColumnCount() > 0) {
            jTableOut.getColumnModel().getColumn(0).setResizable(false);
            jTableOut.getColumnModel().getColumn(1).setResizable(false);
            jTableOut.getColumnModel().getColumn(2).setResizable(false);
            jTableOut.getColumnModel().getColumn(3).setResizable(false);
            jTableOut.getColumnModel().getColumn(4).setResizable(false);
            jTableOut.getColumnModel().getColumn(5).setResizable(false);
            jTableOut.getColumnModel().getColumn(6).setResizable(false);
            jTableOut.getColumnModel().getColumn(7).setResizable(false);
            jTableOut.getColumnModel().getColumn(8).setResizable(false);
            jTableOut.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Outgoing", jPanel2);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Airport Code");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(657, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Settings", jPanel4);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Flight ID (100000-99999)");

        jTextA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextA1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Carrier (XXX)");

        jLabel3.setText("Destination (XXX)");

        jLabel4.setText("Source (XXX)");

        jLabel5.setText("Departure (00:00)");

        jLabel6.setText("Arrival (00:00)");

        jLabel7.setText("Status");

        jTextA9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextA9ActionPerformed(evt);
            }
        });

        jLabel8.setText("Plane ID (XX-999)");

        jLabel10.setText("Gate (999)");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextA1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(jTextA3)
                        .addComponent(jTextA5)
                        .addComponent(jTextA6))
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(54, 54, 54)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextA2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextA4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextA8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextA9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextA7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextA8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(82, 82, 82)))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextA9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)))
                        .addComponent(jButton1))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextA7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextA6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Add Flight", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Edit Flight", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Delete Flight", jPanel10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CRUD", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //This method deletes every row of the table that is displayed on the gui so that updated one can be placed
    private void clearTable(DefaultTableModel model) {
        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); ++i) {
                model.removeRow(i);
            }
        }
    }

    //Valides user input and provides error/success messages
    private boolean validateFlight(int flightId, String planeId, String carrier, String dest, String source, String depart, String arriv, int gate, String status) {
        if (!(flightId >= 100000 && flightId <= 999999)) {
            //flightId must be unique
            System.out.println("Flight id regex");
            JOptionPane.showMessageDialog(null, "Please enter flightID accordingly(ex./ '100000')", "AirportX", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!(allFlights.stream().noneMatch((f) -> (f.getFlightId() == flightId)))) {
            System.out.println("id match");
            JOptionPane.showMessageDialog(null, "Matching flightID, please enter a unique ID.", "AirportX", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if ("".equals(planeId) || !planeId.matches("([A-Z][A-Z])(-)+([0-9][0-9][0-9])")) {
            System.out.println(planeId);
            System.out.println("regex");
            JOptionPane.showMessageDialog(null, "Please enter planeID accordingly(ex./ 'AA-955')", "AirportX", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if ("".equals(carrier) || !carrier.matches("([A-Z][A-Z][A-Z])")) {
            System.out.println(carrier);
            System.out.println("regex");
            JOptionPane.showMessageDialog(null, "Please enter carrier accordingly(ex./ 'AAA')", "AirportX", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if ("".equals(dest) || !dest.matches("([A-Z][A-Z][A-Z])")) {
            System.out.println(carrier);
            System.out.println("regex");
            JOptionPane.showMessageDialog(null, "Please enter dest accordingly(ex./ 'AAA')", "AirportX", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if ("".equals(source) || !source.matches("([A-Z][A-Z][A-Z])")) {
            System.out.println(carrier);
            System.out.println("regex");
            JOptionPane.showMessageDialog(null, "Please enter source accordingly(ex./ 'AAA')", "AirportX", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if ("".equals(depart) || !depart.matches("([0-9][0-9])(:)+([0-9][0-9])")) {
            System.out.println(carrier);
            System.out.println("regex");
            JOptionPane.showMessageDialog(null, "Please enter departing time accordingly(ex./ '99:99')", "AirportX", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if ("".equals(arriv) || !arriv.matches("([0-9][0-9])(:)+([0-9][0-9])")) {
            System.out.println(carrier);
            System.out.println("regex");
            JOptionPane.showMessageDialog(null, "Please enter arriving time accordingly(ex./ '99:99')", "AirportX", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Button for submiting a new Flight
        //Used try-catch and an if statement to validate input and respond to user
        try {
            if (validateFlight(Integer.parseInt(jTextA1.getText()), jTextA2.getText(), jTextA3.getText(), jTextA4.getText(), jTextA5.getText(), jTextA6.getText(),
                    jTextA7.getText(), Integer.parseInt(jTextA8.getText()), jTextA9.getText())) {

                allFlights.add(new Flight(Integer.parseInt(jTextA1.getText()),
                        jTextA2.getText(), jTextA3.getText(), jTextA4.getText(), jTextA5.getText(),
                        jTextA6.getText(), jTextA7.getText(), null, Integer.parseInt(jTextA8.getText()), jTextA9.getText()));
                JOptionPane.showMessageDialog(null, "Flight Added", "AirportX", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter fields accordingly", "AirportX", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextA1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        //Creates a table model, fills it with current flight info depending on the selected airport and puts it on the gui
        
        DefaultTableModel defaultModel = (DefaultTableModel) jTableIn.getModel();
        DefaultTableModel defaultModel1 = (DefaultTableModel) jTableOut.getModel();
        clearTable(defaultModel);
        clearTable(defaultModel1);

        currentAirport = allAirports.get(jComboBox1.getSelectedIndex()).getCode();
        System.out.println(currentAirport);

        int index = 0;
        for (Airport airport : allAirports) {
            if (Objects.equals(airport.getCode(), currentAirport)) {
                index = allAirports.indexOf(airport);
                break;
            }
        }
        ArrayList<Flight> arrs = allAirports.get(index).incoming(allFlights);

        for (Flight arr : arrs) {
            if (arr.getFlightId() != 00000) {

                Vector newRow = new Vector();

                newRow.add(arr.getFlightId());
                newRow.add(arr.getPlaneId());
                newRow.add(arr.getCarrier());
                newRow.add(arr.getSource());
                newRow.add(arr.getDest());
                newRow.add(arr.getDepart());
                newRow.add(arr.getArriv());
                newRow.add("crew");
                newRow.add(arr.getGate());
                newRow.add(arr.getStatus());

                defaultModel.addRow(newRow);
            }
        }

        ArrayList<Flight> arrs1 = allAirports.get(index).outgoing(allFlights);

        for (Flight arr : arrs1) {
            if (arr.getFlightId() != 00000) {

                Vector newRow = new Vector();

                newRow.add(arr.getFlightId());
                newRow.add(arr.getPlaneId());
                newRow.add(arr.getCarrier());
                newRow.add(arr.getSource());
                newRow.add(arr.getDest());
                newRow.add(arr.getDepart());
                newRow.add(arr.getArriv());
                newRow.add("crew");
                newRow.add(arr.getGate());
                newRow.add(arr.getStatus());

                defaultModel1.addRow(newRow);
            }
        }


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextA9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextA9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextA9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirportXUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirportXUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirportXUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirportXUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        InputStream in;
        try {
            in = new FileInputStream(new File("Gui_Music.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirportXUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableIn;
    private javax.swing.JTable jTableOut;
    private javax.swing.JTextField jTextA1;
    private javax.swing.JTextField jTextA2;
    private javax.swing.JTextField jTextA3;
    private javax.swing.JTextField jTextA4;
    private javax.swing.JTextField jTextA5;
    private javax.swing.JTextField jTextA6;
    private javax.swing.JTextField jTextA7;
    private javax.swing.JTextField jTextA8;
    private javax.swing.JTextField jTextA9;
    // End of variables declaration//GEN-END:variables
}
